name: recette_plus
description: "Une application de recettes moderne et intuitive"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Secure storage
  flutter_secure_storage: ^9.0.0

  # State management
  flutter_riverpod: ^2.4.0
  provider: ^6.1.1

  # Supabase
  supabase_flutter: ^2.3.4

  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  # Google Sign In natif pour Android
  google_sign_in: ^6.2.1

  # Image handling - versions compatibles
  image_picker: ^1.0.7

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Location & Maps - Enhanced
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Video - Enhanced
  video_player: ^2.10.0

  # HTTP requests for geocoding and enhanced features
  http: ^1.1.0

  # JSON handling
  json_annotation: ^4.8.1

  # Connectivity - Enhanced
  connectivity_plus: ^6.0.5

  # Crypto for security
  crypto: ^3.0.3

dev_dependencies:
  mockito: ^5.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700